# Generated by Django 3.0.2 on 2020-01-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_room',
            field=models.ManyToManyField(blank=True, to='classes.ClassRoom'),
        ),
    ]
